/**
 * Phase 1D — Additional export formats.
 *
 * Three formats are supported:
 *   - HTML (existing `lib/report/render.ts:renderReportHtml`) — browser
 *     "print-to-PDF" path. Avoids the heavy `@react-pdf/renderer` dep.
 *   - JSON (this module) — raw structured data dump.
 *   - Markdown (this module) — human-readable narrative.
 */

import type { Evidence, Session, Verdict } from '@/lib/types'

/**
 * Stable JSON export — sorts keys deterministically so identical sessions
 * produce identical hashes (useful for the share-link path).
 */
export function renderReportJson(session: Session): string {
  return JSON.stringify(session, sortReplacer, 2)
}

function sortReplacer(_key: string, value: unknown): unknown {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    const obj = value as Record<string, unknown>
    const sorted: Record<string, unknown> = {}
    for (const k of Object.keys(obj).sort()) sorted[k] = obj[k]
    return sorted
  }
  return value
}

/**
 * Markdown export — sections are stable and parseable. Used as the body
 * of share links and as a copy-to-clipboard target in the UI.
 */
export function renderReportMarkdown(session: Session): string {
  const lines: string[] = []
  const created = new Date(session.createdAt).toLocaleString()
  lines.push(`# Veritas Fact-Check Report`)
  lines.push(``)
  lines.push(`- Session: \`${session.id}\``)
  lines.push(`- Created: ${created}`)
  lines.push(`- Input mode: ${session.inputMode}`)
  lines.push(`- Claims checked: ${session.verdicts.length}`)
  lines.push(``)

  if (session.speakers.length > 0) {
    lines.push(`## Per-speaker accuracy`)
    lines.push(``)
    lines.push(`| Speaker | Claims | Verified | False | Misleading | Contested | Unverified | Accuracy |`)
    lines.push(`|---------|-------:|---------:|------:|-----------:|----------:|-----------:|---------:|`)
    for (const s of session.speakers) {
      lines.push(
        `| ${s.label} | ${s.claimsTotal} | ${s.claimsVerified} | ${s.claimsFalse} | ${s.claimsMisleading} | ${s.claimsContested ?? 0} | ${s.claimsUnverified} | ${s.accuracyPct}% |`,
      )
    }
    lines.push(``)
  }

  if (session.verdicts.length === 0) {
    lines.push(`No verdicts recorded.`)
    return lines.join('\n')
  }

  // Group verdicts by speaker for the per-speaker sections.
  const grouped = new Map<string, Verdict[]>()
  for (const v of session.verdicts) {
    const arr = grouped.get(v.speaker) ?? []
    arr.push(v)
    grouped.set(v.speaker, arr)
  }
  const speakers = Array.from(grouped.keys()).sort()

  lines.push(`## Verdicts`)
  for (const speaker of speakers) {
    lines.push(``)
    lines.push(`### Speaker ${speaker}`)
    const arr = (grouped.get(speaker) ?? []).slice().sort((a, b) =>
      a.timestamp.localeCompare(b.timestamp),
    )
    for (const v of arr) {
      lines.push(``)
      lines.push(`#### ${v.label} — ${v.confidencePct}% confidence · ${v.timestamp}`)
      lines.push(``)
      lines.push(`> ${v.claimText.replace(/\n+/g, ' ')}`)
      lines.push(``)
      lines.push(v.explanation || 'No explanation produced.')
      if (v.evidence.length > 0) {
        lines.push(``)
        lines.push(`**Evidence:**`)
        for (const e of v.evidence) {
          lines.push(`- [${e.source}](${e.url}) — ${e.stance} · credibility ${e.credibilityScore}`)
        }
      }
      if (v.counterEvidence && v.counterEvidence.length > 0) {
        lines.push(``)
        lines.push(`**Counter-evidence:**`)
        for (const e of v.counterEvidence) {
          lines.push(`- [${e.source}](${e.url}) — ${e.stance} · credibility ${e.credibilityScore}`)
        }
      }
      if (v.rhetoricalPattern) {
        lines.push(``)
        lines.push(`**Rhetorical pattern detected:** \`${v.rhetoricalPattern}\``)
      }
    }
  }

  lines.push(``)
  lines.push(`---`)
  lines.push(`Generated by Veritas — the truth machine.`)
  return lines.join('\n')
}

/** Helper for tests / callers that want the formatted evidence list only. */
export function formatEvidenceMarkdown(evidence: Evidence[]): string {
  return evidence
    .map((e) => `- [${e.source}](${e.url}) — ${e.stance} · credibility ${e.credibilityScore}`)
    .join('\n')
}
